### PR TITLE
Switch to CommandAPI

### PR DESCRIPTION
**Pull request by lowercasebtw**
I believe commandapi is a well-made library which allows easy use of brigadier addding useful features and is also cleaner.

I have swapped out the system you were using prior with it, with nice autocomplete & also /cd create now autocompletes file names :)

Syntax is relatively the same/is backwards compatible but you can now do this which I don't think you could do prior

/cd create x.mp3 oneword   (No quotes)
/cd download "https://????" x.mp3   (Has quotes for the url)

### CODE REVIEW

**Comment by lowercasebtw** [comment]
Besides this switching to commandapi and already mentioned, this adds a feature

Auto complete for the file names

**Comment by lowercasebtw** [comment]
Also updated gradle / switched out the shade library which was used and was outdated

**Comment by lowercasebtw** [comment]
Overall its just better

**Comment by Navoei** [comment]
Nice work! I really like this!

**Comment by lowercasebtw** [comment]
:)

**Pull request merged**
